name: PR Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_commit_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message format
        run: |
          COMMIT_MESSAGES=$(git log --format=%B $GITHUB_BASE_REF..$GITHUB_SHA)
          for COMMIT_MESSAGE in $COMMIT_MESSAGES; do
            if ! [[ "$COMMIT_MESSAGE" =~ ^(feat|fix|docs|chore|style|refactor|test):\ .+ ]]; then
              echo "Error: Commit message '$COMMIT_MESSAGE' does not follow the required format"
              exit 1
            fi
            if [[ "$COMMIT_MESSAGE" =~ (Closes|Fixes|Resolves)\ #[0-9]+ ]]; then
              ISSUE_KEY=$(echo "$COMMIT_MESSAGE" | grep -oE '(Closes|Fixes|Resolves)\ #[0-9]+')
              echo "Success: Found valid issue reference: $ISSUE_KEY"
            else
              echo "Error: Commit message '$COMMIT_MESSAGE' does not reference an issue with 'Closes #<issue_number>' or 'Fixes #<issue_number>'"
              exit 1
            fi
          done
